services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,lambda,dynamodb,sqs,sns,apigateway,iam,cloudwatch
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:-}  # Para la versi√≥n Pro
    volumes:
      - "localstack-volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network

volumes:
  localstack-volume:  

networks:
  localstack-network:
    name: localstack-network