prometheus:
  service:
    type: NodePort
    nodePort: 30000
  prometheusSpec:
    # This configuration tells Prometheus to look for ServiceMonitors 
    # in these specific namespaces, rather than just its own.
    serviceMonitorNamespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - monitoring
          - mi-app
grafana:
  adminPassword: "admin123"
  service:
    type: NodePort
    nodePort: 30001

alertmanager:
  service:
    type: NodePort
    nodePort: 30002