name: Security Scan & Security dockerfile

on:
    push:
        branches: [d46_develop]
    workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: constuir imagen
        run: |
            cd ./s7/d46/fast-api
            docker build -t ${{ secrets.DOCKER_USERNAME }}/fast-api-basic:${{ github.sha }} .
            docker push ${{ secrets.DOCKER_USERNAME }}/fast-api-basic:${{ github.sha }}
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - name: Run Trivy
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH ${{ secrets.DOCKER_USERNAME }}/fast-api-basic:${{ github.sha }}